[package]
name = "activatecontaineruid"
version = "0.1.0"
authors = ["Hongli Lai <honglilai@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
incremental = false
panic = "abort"

[dependencies]
yaml-rust = "0.4"
log = "0.4.6"
simple_logger = "1.2.0"
nix = "0.14.0"
failure = "0.1.5"
pwd = "1.3.0"
libc = "0.2"
