name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --color=always --verbose
    - name: Run tests
      run: cargo test --color=always --verbose
