name: Rust

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.png'
      - '*.jpg'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
    - name: Build
      run: cargo build --color=always --verbose
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.integration-test-base
        tags: matchhostfsowner-integration-test-base
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
    - name: Run tests
      run: cargo test --color=always --verbose
